#
#   Dois exemplos aqui
#
#       -  Uma configuração que usa um repositorio git como backend
#       -  Uma configuração baseada em arquivo  (Não recomendado)
#
####################################

server:
  port: ${PORT:8888}

spring:
  application:
    name: configserver

  cloud:
    config:

      discovery:
        enabled: true

      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/natanaelfonseca/msc-configurations/
          searchPaths: ms1,ms2,booksws,contractsws,stockws
          username: natanael.vaz@gmail.com
          password: 

#Configuracoes relacionadas ao registro no eureka
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
      healthcheck:
        enabled: true

#Configuracoes relacionadas ao Actuator
info:
  app:
    name:@project.name@
    description:@project.description@
    version:@project.version@

####
#Classpath e solucao baseada em arquivo
####

#server:
#   port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#           native:
#              searchLocations: file:///home/natanael/confsvr/ms1,
#                               file:///home/natanael/confsvr/ms2
###              #searchLocations: classpath:config/ms1,classpath:config/ms2