#
#   Dois exemplos aqui
#
#       -  Uma configuração que usa um repositorio git como backend
#       -  Uma configuração baseada em arquivo  (Não recomendado)
#
####################################
server:
  port: 8888
  
spring:
  application:
    name: msc-configserver
    
  cloud:
    config:
    
      discovery:
        enabled: true
    
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/natanaelfonseca/msc-configurations/
          searchPaths: ms1,ms2
          username: natanael.vaz@gmail.com
          password: ${gitpassword}

#Configuracoes relacionadas ao registro no eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
      
#Configuracoes relacionadas ao Actuator
info:
  app:
    name: Spring Cloud Config Service
    description: All stuff related to Configurations is Here
    version: 1.0.0



####
#Classpath e solucao baseada em arquivo
####

#server:
#   port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#           native:
#              searchLocations: file:///home/natanael/confsvr/ms1,
#                               file:///home/natanael/confsvr/ms2
###              #searchLocations: classpath:config/ms1,classpath:config/ms2